import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout";

export const metadata: Metadata = {
  title: "Bestore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <footer className="w-full bg-yellow-50 h-[60px] flex items-center mt-12 py-2 justify-center flex-col pt-3">
          <img className="w-[30px]" src="/images/logo.png" alt="logo" />
          <h3 className="text-lg text-red-500 cursive mt-1">BeStore</h3>
        </footer>
      </body>
    </html>
  );
}
